In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
!pip install arch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.7/981.7 kB 10.0 MB/s eta 0:00:00


In [3]:
from arch.bootstrap import IIDBootstrap, IndependentSamplesBootstrap

Необходимо построить бутстрэп доверительный интервал для отношения дисперсий двух выборок с нормальным распределением

In [5]:
seed = 23657
rng = np.random.default_rng(seed)

In [6]:
x2 = rng.normal(loc=7, scale=3, size=20)

In [8]:
x2

array([12.8578398 ,  7.1468781 ,  9.0281624 ,  8.05529705,  7.28632503,
        2.30409598,  3.98660136, 10.8469175 ,  8.15560909,  4.75338016,
        7.45931438,  7.73159378,  2.28198687, 10.09313052,  6.19647089,
        4.92850185,  7.36899996,  5.61379521,  4.10366544,  9.01171084])

In [18]:
x1 = rng.normal(loc=2, scale=1, size=20)

In [19]:
x1

array([3.08881794, 1.54376261, 0.48940991, 1.46356173, 1.34479243,
       2.52021441, 1.52674265, 1.78365288, 2.06652269, 2.14419059,
       2.82309349, 1.13919417, 3.00733626, 3.49230463, 2.87794718,
       1.58435841, 2.3402208 , 2.95059949, 2.59768627, 3.8365093 ])

In [20]:
def var_ratio(x, y):
  return (np.std(y))**2 / (np.std(x))**2

In [21]:
boot_x1_x2 = IndependentSamplesBootstrap(x1, x2, seed = 23657)
boot_x1_x2.conf_int(var_ratio, reps=10000, size=0.95, method='basic')

array([[-1.88775717],
       [15.86436369]])

D(x2) = 9, D(x1) = 1 -> D(x2)/D(x1) = 9 попадает в построенный доверительный интервал -> доверительный интервал построен верно